# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'hluser' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for hluser
	
  pod 'Firebase/Core'
  pod 'Firebase/Auth'


  target 'hluserTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'hluser-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for hluser-tvOS

  target 'hluser-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
